project_id: 590927
preserve_hierarchy: true
files:
  - source: public/locales/en/common.json
    translation: /public/locales/%two_letters_code%/common.json
  - source: public/locales/en/onboarding.json
    translation: /public/locales/%two_letters_code%/onboarding.json
